version: '3.4'

services:
  todoapi:
    image: ${DOCKER_REGISTRY-}todoapi
    build:
      context: API
      dockerfile: src/Dockerfile
  nuxt-app:
    image: ${DOCKER_REGISTRY-}todoclient
    build:
      context: Client
      dockerfile: Dockerfile
    container_name: academy_todo_2021_frontend
    restart: always
    ports:
      - "3000:3000"
    command: "npm run start"
